# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0014_auto_20180318_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='user',
        ),
    ]
