# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 00:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0016_auto_20180318_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Neighborhood',
        ),
        migrations.AddField(
            model_name='profile',
            name='Neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch.Neighborhood'),
        ),
    ]
