# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_auto_20180318_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
