# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0008_auto_20180318_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='neighborhood_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='neighborhood_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
