# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 00:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch', '0012_remove_neighborhood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
